### PR TITLE
UPDATE ETC_BP - Translated map names. Lines: 9559 - 9638

### PR DESCRIPTION
**Pull request by faicciruz**
I updated this file with the corresponding map names:

https://github.com/Treeofsavior/PortugueseTranslation/wiki/Tradu%C3%A7%C3%A3o-de-Lugares

There are a few untranslated areas, but I'll update this file once all the new maps I added to the link above get a translation

Please check the wiki link and add your translation. The only map with a weird translation there is Fazenda Tenants, Fazenda dos Inquilinos or something along this line.

### CODE REVIEW

**Comment by faicciruz** [comment]
Despite the wiki reference be just a draft, I sent the translated names anyway. It isn't hard to locate/substitute the names in case they get changed in the future.

**Comment by faicciruz** [comment]
I accidentally deleted the original repository. If errors are found, I'll have to close this PR and open a new one.

**Comment by faicciruz** [comment]
Good to merge!

I only copied and pasted these names from our wiki table. If one of them get changed in the future, I'll make sure to update the file.

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
