### PR TITLE
Revert "UI_BP.tsv UI_20150317_001251 to UI_20150317_001400"

### PR DESCRIPTION
**Pull request by BrasilToS**
Reverts Treeofsavior/PortugueseTranslation#70

Hellow IMC Games, I've noticed that you guys merged this one wrong.
Your merge is 100 lines ahead of my pull.

Instead of 1351 to 1500
you should put it from 1251 to 1400

Thank you.

### CODE REVIEW

**Comment by imcgames** [comment]
Hello @BrasilToS 
Please leave comment like "Good to Merge" , if the PR is no need more an additional edit. Then we can start Merge. Thank you. :+1:

**Comment by BrasilToS** [comment]
Ok, as soon as possible.

**Comment by BrasilToS** [comment]
https://github.com/BrasilToS/PortugueseTranslation/commit/841a3a9cf852986c627002d7d91959e6cfbc0c5b

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
