### PR TITLE
UPDATE ETC_BP - Translated a few lines in a non-linear way.

### PR DESCRIPTION
**Pull request by faicciruz**
All this translation was reviewed in-game, it doesn't follow a linear way because I was translating related content, this way I can guarantee that everything will make perfect sense.

### CODE REVIEW

**Comment by faicciruz** [comment]
I accidentally deleted the original repository. If errors are found, I'll have to close this PR and open a new one.

**Comment by faicciruz** [comment]
This file still needs to be reviewed by someone else. In case anything changed or if it's conflicting with another file, I'll create a new PR.

**Comment by faicciruz** [comment]
I'm now able to edit the file. GitHub recovered my deleted fork.

**Comment by faicciruz** [comment]
I wish I had access to the game so I could review this file once again.

**Comment by imcgames** [comment]
Thank you :+1:

**Pull request merged**
