### PR TITLE
UI_BP.tsv UI_20150317_001701 to UI_20150317_001831

### PR DESCRIPTION
**Pull request by BrasilToS**
Last part, finally!

### CODE REVIEW

**Comment by BrasilToS** [comment]
Changed:
Informações de grupos próximos
to
Grupos Próximos
To fit with the UI.

**Comment by imcgames** [comment]
Please leave a comment like "Good to merge" for us to understand it's correct PR or not. Thank you.

**Comment by BrasilToS** [comment]
Por favor pessoal, chequem a minha ultima atualização deste arquivo https://github.com/BrasilToS/PortugueseTranslation/commit/e9d74872bc12f463c24cccee963b2991b1488e82

**Comment by BrasilToS** [comment]
Good to Merge :+1:

**Comment by imcgames** [comment]
:+1:

**Pull request merged**
